"""
make_curve_subsets.py — build the data-quantity LEARNING CURVE inputs.

Question we're testing (cheaply, on data we already have): does best UNSEEN-ECAPA rise as we add
training clips? If yes -> the model is data-starved -> quantity is a real lever. If flat -> saturated
-> more data won't help and we save weeks of collecting lectures.

Makes NESTED subsets (35 ⊂ 70 ⊂ 105 ⊂ 140) of the training manifest + one LoRA config per subset
(identical to voxcpm_lora.yaml except the manifest, output paths, and a short step budget with frequent
checkpoints so each subset's own peak is captured). Run locally, then commit + push so the pod clones them.
Run -> .venv/Scripts/python.exe scripts/make_curve_subsets.py
"""
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FINAL = ROOT / "data/out/lecture1/final"
SRC = FINAL / "train.voxcpm.jsonl"
CLOUD = ROOT / "cloud"

SIZES = [35, 70, 105, 140]
SEED = 20260630
MAX_STEPS = 250        # generous; small subsets peak early, we keep every checkpoint
SAVE_INTERVAL = 25     # frequent -> captures each subset's own (early) peak
WARMUP = 40

YAML = """# AUTO-GENERATED by make_curve_subsets.py — learning-curve subset n{N} ({N}/140 clips).
# Identical to voxcpm_lora.yaml except: train_manifest, save_path, tensorboard, step budget.
pretrained_path: /workspace/VoxCPM2
train_manifest: /workspace/voice-cloning/data/out/lecture1/final/train_n{N}.voxcpm.jsonl
val_manifest:
sample_rate: 16000
out_sample_rate: 48000
batch_size: 2
grad_accum_steps: 8
num_workers: 2
num_iters: {steps}
log_interval: 10
valid_interval: 100
save_interval: {save}
learning_rate: 0.0001
weight_decay: 0.01
warmup_steps: {warmup}
max_steps: {steps}
max_batch_tokens: 8192
save_path: /workspace/ckpt/curve_n{N}
tensorboard: /workspace/logs/curve_n{N}
lambdas:
  loss/diff: 1.0
  loss/stop: 1.0
lora:
  enable_lm: true
  enable_dit: true
  enable_proj: false
  r: 32
  alpha: 32
  dropout: 0.0
"""


def main():
    lines = [l for l in SRC.read_text(encoding="utf-8").splitlines() if l.strip()]
    print(f"source manifest: {len(lines)} clips")
    order = lines[:]
    random.Random(SEED).shuffle(order)          # one fixed shuffle -> nested subsets
    for n in SIZES:
        man = FINAL / f"train_n{n}.voxcpm.jsonl"
        man.write_text("\n".join(order[:n]) + "\n", encoding="utf-8")
        (CLOUD / f"voxcpm_lora_n{n}.yaml").write_text(
            YAML.format(N=n, steps=MAX_STEPS, save=SAVE_INTERVAL, warmup=WARMUP), encoding="utf-8")
        print(f"  n{n}: {man.name} ({n} clips) + cloud/voxcpm_lora_n{n}.yaml")
    print("done. commit + push so the pod gets them.")


if __name__ == "__main__":
    main()
